// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type HelloResponseDto = {
    /**
     * Greeting message
     */
    message: string;
};

export type RegisterDto = {
    name: string;
    username: string;
    displayUsername?: string;
    email: string;
    password: string;
};

export type AuthUserDto = {
    id: string;
    email: string;
    name: string;
    username?: {
        [key: string]: unknown;
    };
    displayUsername?: {
        [key: string]: unknown;
    };
    image?: {
        [key: string]: unknown;
    };
    emailVerified?: boolean;
};

export type AuthSessionResponseDto = {
    user: AuthUserDto;
    /**
     * JWT access token (15 min)
     */
    accessToken: string;
};

export type LoginDto = {
    /**
     * Email address or username
     */
    login: string;
    password: string;
};

export type AuthRefreshResponseDto = {
    /**
     * JWT access token (15 min)
     */
    accessToken: string;
};

export type OkResponseDto = {
    ok: boolean;
};

export type UsernameAvailableDto = {
    username: string;
};

export type UsernameAvailableResponseDto = {
    available: boolean;
};

export type ForgotPasswordDto = {
    email: string;
    redirectTo?: string;
};

export type ResetPasswordDto = {
    /**
     * Password reset token from email link
     */
    token: string;
    newPassword: string;
};

export type VerifyEmailDto = {
    /**
     * Email verification token from the link
     */
    token: string;
};

export type ResendVerificationDto = {
    email: string;
};

export type VerifyOneTimeTokenDto = {
    /**
     * One-time token from OAuth bridge redirect
     */
    token: string;
};

export type GithubConnectionResponseDto = {
    connected: boolean;
    githubUsername?: string;
    scopes?: {
        [key: string]: unknown;
    };
};

export type GithubRepoDto = {
    githubId: number;
    fullName: string;
    name: string;
    owner: string;
    defaultBranch: string;
    private: boolean;
    htmlUrl: string;
    /**
     * Whether this repo is already linked to the account
     */
    linked: boolean;
};

export type GithubRepoListResponseDto = {
    repositories: Array<GithubRepoDto>;
};

export type LinkedRepositoryResponseDto = {
    id: string;
    githubId: number;
    fullName: string;
    name: string;
    owner: string;
    defaultBranch: string;
    private: boolean;
    htmlUrl: string;
    linkedAt: string;
};

export type LinkedRepositoryListResponseDto = {
    repositories: Array<LinkedRepositoryResponseDto>;
};

export type LinkRepositoriesDto = {
    /**
     * GitHub repository IDs to link
     */
    githubIds: Array<number>;
};

export type LinkRepositoriesResponseDto = {
    linked: Array<LinkedRepositoryResponseDto>;
};

export type RepositoryTriggersDto = {
    release: boolean;
    tagPush: boolean;
    branchPush: boolean;
};

export type WebhookManualSetupDto = {
    url: string;
    secret: string;
    instructions: string;
};

export type RepositoryWebhookStatusDto = {
    status: 'pending' | 'active' | 'manual_required' | 'error' | 'not_configured';
    lastDeliveryAt?: string | null;
    lastError?: string | null;
    manualSetup?: WebhookManualSetupDto | null;
};

export type LinkedRepositoryDetailResponseDto = {
    id: string;
    githubId: number;
    fullName: string;
    name: string;
    owner: string;
    defaultBranch: string;
    private: boolean;
    htmlUrl: string;
    linkedAt: string;
    triggers: RepositoryTriggersDto;
    activeTriggerCount: number;
    webhook: RepositoryWebhookStatusDto;
};

export type RepositoryTriggersResponseDto = {
    triggers: RepositoryTriggersDto;
    webhook: RepositoryWebhookStatusDto;
};

export type UpdateRepositoryTriggersDto = {
    release: boolean;
    tagPush: boolean;
    branchPush: boolean;
};

export type TriggerEventResponseDto = {
    id: string;
    eventType: string;
    triggerType: string;
    summary: string;
    status: string;
    shoutoutId?: string | null;
    createdAt: string;
};

export type TriggerEventListResponseDto = {
    events: Array<TriggerEventResponseDto>;
};

export type ShoutoutResponseDto = {
    id: string;
    title: string;
    status: string;
    linkedRepositoryId: string;
    repositoryFullName: string;
    triggerType: string;
    createdAt: string;
};

export type ShoutoutListResponseDto = {
    shoutouts: Array<ShoutoutResponseDto>;
};

export type ShoutoutDetailResponseDto = {
    id: string;
    title: string;
    status: string;
    linkedRepositoryId: string;
    repositoryFullName: string;
    triggerType: string;
    createdAt: string;
    sourceSummary: {
        [key: string]: unknown;
    };
    triggerEventId: string;
};

export type SubscriptionPlanLimitsDto = {
    repos: number;
    /**
     * null means unlimited
     */
    releasesPerMonth?: {
        [key: string]: unknown;
    } | null;
};

export type SubscriptionPlanResponseDto = {
    name: string;
    displayName: string;
    trialDays?: {
        [key: string]: unknown;
    } | null;
    limits: SubscriptionPlanLimitsDto;
    isBillable: boolean;
};

export type SubscriptionPlansListResponseDto = {
    plans: Array<SubscriptionPlanResponseDto>;
};

export type SubscriptionMeResponseDto = {
    plan: string;
    status?: {
        [key: string]: unknown;
    } | null;
    periodEnd?: {
        [key: string]: unknown;
    } | null;
    stripeSubscriptionId?: {
        [key: string]: unknown;
    } | null;
    limits: SubscriptionPlanLimitsDto;
};

export type PaymentInvoiceDto = {
    id: string;
    amountDue: number;
    currency: string;
    status?: {
        [key: string]: unknown;
    } | null;
    createdAt: string;
    hostedInvoiceUrl?: {
        [key: string]: unknown;
    } | null;
};

export type PaymentsListResponseDto = {
    invoices: Array<PaymentInvoiceDto>;
};

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetHelloResponses = {
    /**
     * Get Hello
     */
    200: HelloResponseDto;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];

export type HealthControllerCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthControllerCheckErrors = {
    /**
     * The Health Check is not successful
     */
    503: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthControllerCheckError = HealthControllerCheckErrors[keyof HealthControllerCheckErrors];

export type HealthControllerCheckResponses = {
    /**
     * The Health Check is successful
     */
    200: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthControllerCheckResponse = HealthControllerCheckResponses[keyof HealthControllerCheckResponses];

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * Validation or auth error
     */
    400: unknown;
    /**
     * Email or username already exists
     */
    409: unknown;
};

export type AuthControllerRegisterResponses = {
    201: AuthSessionResponseDto;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type AuthControllerLoginResponses = {
    200: AuthSessionResponseDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type AuthControllerSessionResponses = {
    /**
     * Null when unauthenticated
     */
    200: AuthSessionResponseDto;
};

export type AuthControllerSessionResponse = AuthControllerSessionResponses[keyof AuthControllerSessionResponses];

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * Invalid or expired refresh token
     */
    401: unknown;
};

export type AuthControllerRefreshResponses = {
    200: AuthRefreshResponseDto;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    200: OkResponseDto;
};

export type AuthControllerLogoutResponse = AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses];

export type AuthControllerIsUsernameAvailableData = {
    body: UsernameAvailableDto;
    path?: never;
    query?: never;
    url: '/auth/username/available';
};

export type AuthControllerIsUsernameAvailableResponses = {
    200: UsernameAvailableResponseDto;
};

export type AuthControllerIsUsernameAvailableResponse = AuthControllerIsUsernameAvailableResponses[keyof AuthControllerIsUsernameAvailableResponses];

export type AuthControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type AuthControllerForgotPasswordResponses = {
    200: OkResponseDto;
};

export type AuthControllerForgotPasswordResponse = AuthControllerForgotPasswordResponses[keyof AuthControllerForgotPasswordResponses];

export type AuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type AuthControllerResetPasswordErrors = {
    /**
     * Invalid or expired token
     */
    400: unknown;
};

export type AuthControllerResetPasswordResponses = {
    200: OkResponseDto;
};

export type AuthControllerResetPasswordResponse = AuthControllerResetPasswordResponses[keyof AuthControllerResetPasswordResponses];

export type AuthControllerVerifyEmailData = {
    body: VerifyEmailDto;
    path?: never;
    query?: never;
    url: '/auth/verify-email';
};

export type AuthControllerVerifyEmailErrors = {
    /**
     * Invalid or expired token
     */
    400: unknown;
};

export type AuthControllerVerifyEmailResponses = {
    200: OkResponseDto;
};

export type AuthControllerVerifyEmailResponse = AuthControllerVerifyEmailResponses[keyof AuthControllerVerifyEmailResponses];

export type AuthControllerResendVerificationData = {
    body: ResendVerificationDto;
    path?: never;
    query?: never;
    url: '/auth/resend-verification';
};

export type AuthControllerResendVerificationResponses = {
    200: OkResponseDto;
};

export type AuthControllerResendVerificationResponse = AuthControllerResendVerificationResponses[keyof AuthControllerResendVerificationResponses];

export type AuthControllerOauthBridgeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/oauth/bridge';
};

export type AuthControllerVerifyOneTimeTokenData = {
    body: VerifyOneTimeTokenDto;
    path?: never;
    query?: never;
    url: '/auth/one-time-token/verify';
};

export type AuthControllerVerifyOneTimeTokenErrors = {
    /**
     * Invalid or expired token
     */
    400: unknown;
};

export type AuthControllerVerifyOneTimeTokenResponses = {
    200: AuthSessionResponseDto;
};

export type AuthControllerVerifyOneTimeTokenResponse = AuthControllerVerifyOneTimeTokenResponses[keyof AuthControllerVerifyOneTimeTokenResponses];

export type AuthControllerGoogleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerGithubData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/github';
};

export type DisconnectGithubData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/repositories/github/connection';
};

export type DisconnectGithubResponses = {
    /**
     * Disconnect Github
     */
    204: void;
};

export type DisconnectGithubResponse = DisconnectGithubResponses[keyof DisconnectGithubResponses];

export type GetGithubConnectionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/repositories/github/connection';
};

export type GetGithubConnectionResponses = {
    /**
     * Get Github Connection
     */
    200: GithubConnectionResponseDto;
};

export type GetGithubConnectionResponse = GetGithubConnectionResponses[keyof GetGithubConnectionResponses];

export type ConnectGithubData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/repositories/github/connect';
};

export type GithubCallbackData = {
    body?: never;
    path?: never;
    query?: {
        code?: unknown;
        state?: unknown;
        error?: unknown;
    };
    url: '/repositories/github/callback';
};

export type ListAvailableReposData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/repositories/github/available';
};

export type ListAvailableReposErrors = {
    /**
     * GitHub is not connected
     */
    400: unknown;
};

export type ListAvailableReposResponses = {
    /**
     * List Available Repos
     */
    200: GithubRepoListResponseDto;
};

export type ListAvailableReposResponse = ListAvailableReposResponses[keyof ListAvailableReposResponses];

export type ListLinkedReposData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/repositories';
};

export type ListLinkedReposResponses = {
    /**
     * List Linked Repos
     */
    200: LinkedRepositoryListResponseDto;
};

export type ListLinkedReposResponse = ListLinkedReposResponses[keyof ListLinkedReposResponses];

export type LinkRepositoriesData = {
    body: LinkRepositoriesDto;
    path?: never;
    query?: never;
    url: '/repositories';
};

export type LinkRepositoriesErrors = {
    /**
     * GitHub is not connected or repository is inaccessible
     */
    400: unknown;
};

export type LinkRepositoriesResponses = {
    /**
     * Link Repositories
     */
    201: LinkRepositoriesResponseDto;
};

export type LinkRepositoriesResponse = LinkRepositoriesResponses[keyof LinkRepositoriesResponses];

export type UnlinkRepositoryData = {
    body?: never;
    path: {
        /**
         * Linked repository id
         */
        id: string;
    };
    query?: never;
    url: '/repositories/{id}';
};

export type UnlinkRepositoryErrors = {
    /**
     * Linked repository not found
     */
    404: unknown;
};

export type UnlinkRepositoryResponses = {
    /**
     * Unlink Repository
     */
    204: void;
};

export type UnlinkRepositoryResponse = UnlinkRepositoryResponses[keyof UnlinkRepositoryResponses];

export type GetLinkedRepositoryDetailData = {
    body?: never;
    path: {
        /**
         * Linked repository id
         */
        id: string;
    };
    query?: never;
    url: '/repositories/{id}';
};

export type GetLinkedRepositoryDetailErrors = {
    /**
     * Linked repository not found
     */
    404: unknown;
};

export type GetLinkedRepositoryDetailResponses = {
    /**
     * Get Linked Repository Detail
     */
    200: LinkedRepositoryDetailResponseDto;
};

export type GetLinkedRepositoryDetailResponse = GetLinkedRepositoryDetailResponses[keyof GetLinkedRepositoryDetailResponses];

export type GetRepositoryTriggersData = {
    body?: never;
    path: {
        /**
         * Linked repository id
         */
        id: string;
    };
    query?: never;
    url: '/repositories/{id}/triggers';
};

export type GetRepositoryTriggersErrors = {
    /**
     * Linked repository not found
     */
    404: unknown;
};

export type GetRepositoryTriggersResponses = {
    /**
     * Get Repository Triggers
     */
    200: RepositoryTriggersResponseDto;
};

export type GetRepositoryTriggersResponse = GetRepositoryTriggersResponses[keyof GetRepositoryTriggersResponses];

export type UpdateRepositoryTriggersData = {
    body: UpdateRepositoryTriggersDto;
    path: {
        /**
         * Linked repository id
         */
        id: string;
    };
    query?: never;
    url: '/repositories/{id}/triggers';
};

export type UpdateRepositoryTriggersErrors = {
    /**
     * Linked repository not found
     */
    404: unknown;
};

export type UpdateRepositoryTriggersResponses = {
    /**
     * Update Repository Triggers
     */
    200: RepositoryTriggersResponseDto;
};

export type UpdateRepositoryTriggersResponse = UpdateRepositoryTriggersResponses[keyof UpdateRepositoryTriggersResponses];

export type ListRepositoryTriggerEventsData = {
    body?: never;
    path: {
        /**
         * Linked repository id
         */
        id: string;
    };
    query?: {
        limit?: string;
    };
    url: '/repositories/{id}/events';
};

export type ListRepositoryTriggerEventsErrors = {
    /**
     * Linked repository not found
     */
    404: unknown;
};

export type ListRepositoryTriggerEventsResponses = {
    /**
     * List Repository Trigger Events
     */
    200: TriggerEventListResponseDto;
};

export type ListRepositoryTriggerEventsResponse = ListRepositoryTriggerEventsResponses[keyof ListRepositoryTriggerEventsResponses];

export type IngestGithubWebhookData = {
    body?: never;
    path: {
        /**
         * Webhook delivery token
         */
        deliveryToken: string;
    };
    query?: never;
    url: '/webhooks/github/{deliveryToken}';
};

export type IngestGithubWebhookErrors = {
    /**
     * Invalid webhook signature
     */
    401: unknown;
    /**
     * Webhook not found
     */
    404: unknown;
};

export type IngestGithubWebhookResponses = {
    /**
     * Ingest Github Webhook
     */
    200: unknown;
};

export type ListShoutoutsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/shoutouts';
};

export type ListShoutoutsResponses = {
    /**
     * List Shoutouts
     */
    200: ShoutoutListResponseDto;
};

export type ListShoutoutsResponse = ListShoutoutsResponses[keyof ListShoutoutsResponses];

export type GetShoutoutData = {
    body?: never;
    path: {
        /**
         * Shoutout id
         */
        id: string;
    };
    query?: never;
    url: '/shoutouts/{id}';
};

export type GetShoutoutErrors = {
    /**
     * Shoutout not found
     */
    404: unknown;
};

export type GetShoutoutResponses = {
    /**
     * Get Shoutout
     */
    200: ShoutoutDetailResponseDto;
};

export type GetShoutoutResponse = GetShoutoutResponses[keyof GetShoutoutResponses];

export type ListSubscriptionPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subscriptions/plans';
};

export type ListSubscriptionPlansResponses = {
    /**
     * List Subscription Plans
     */
    200: SubscriptionPlansListResponseDto;
};

export type ListSubscriptionPlansResponse = ListSubscriptionPlansResponses[keyof ListSubscriptionPlansResponses];

export type GetMySubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subscriptions/me';
};

export type GetMySubscriptionResponses = {
    /**
     * Get My Subscription
     */
    200: SubscriptionMeResponseDto;
};

export type GetMySubscriptionResponse = GetMySubscriptionResponses[keyof GetMySubscriptionResponses];

export type ListMyPaymentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/payments/me';
};

export type ListMyPaymentsResponses = {
    /**
     * List My Payments
     */
    200: PaymentsListResponseDto;
};

export type ListMyPaymentsResponse = ListMyPaymentsResponses[keyof ListMyPaymentsResponses];
